version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./privkey.pem:/etc/nginx/certs/privkey.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always
